import { state } from './state';
import { Track, DrumTrack, MelodyTrack, ChordTrack, TrackMod } from './types';

// ─── Strudel code generation ──────────────────────────────────────────────────

function modifiers(mod: TrackMod, inner: string): string {
  let s = inner;
  if (mod.speed !== 1)       s = `fast(${mod.speed}, ${s})`;
  if (mod.reverse)           s = `rev(${s})`;
  if (mod.palindrome)        s = `palindrome(${s})`;
  if (mod.jux)               s = `jux(rev, ${s})`;
  if (mod.degrade > 0)       s = `degradeBy(${mod.degrade}, ${s})`;
  if (mod.euclid)            s = `euclid(${mod.euclid.n}, ${mod.euclid.k}, ${s})`;
  return s;
}

function fxChain(id: string, fx: typeof state.tracks[0]['fx']): string {
  const parts: string[] = [];
  if (fx.gain  !== 1)     parts.push(`.gain(${fx.gain.toFixed(2)})`);
  if (fx.pan   !== 0)     parts.push(`.pan(${fx.pan.toFixed(2)})`);
  if (fx.room  > 0)       parts.push(`.room(${fx.room.toFixed(2)})`);
  if (fx.delay > 0)       parts.push(`.delay(${fx.delay.toFixed(2)})`);
  if (fx.crush < 16)      parts.push(`.crush(${Math.round(fx.crush)})`);
  if (fx.cutoff < 7900 || fx.cutoff > 8100)
                          parts.push(`.cutoff(${Math.round(fx.cutoff)})`);
  if (fx.res   > 1)       parts.push(`.resonance(${fx.res.toFixed(1)})`);
  return parts.join('');
}

function drumCode(track: DrumTrack): string {
  if (track.muted) return `// ${track.name} (muted)`;
  const pattern = track.steps
    .map(s => s ? 'x' : '~')
    .join(' ');
  const inner = `sound("${track.bank}:${track.sound}")
  .s("${pattern}")`;
  return `${modifiers(track.mod, inner)}${fxChain(track.id, track.fx)}`;
}

function melodyCode(track: MelodyTrack): string {
  if (track.muted) return `// ${track.name} (muted)`;
  const noteStr = track.steps
    .map(n => n ?? '~')
    .join(' ');
  const inner = `note("${noteStr}")
  .sound("${track.synth}")`;

  let s = modifiers(track.mod, inner);

  if (track.mod.arpMode !== 'off') {
    const arps: Record<string,string> = { up:'', down:'.rev()', updown:'.palindrome()', random:'.scramble()' };
    s += arps[track.mod.arpMode] ?? '';
  }
  return `${s}${fxChain(track.id, track.fx)}`;
}

function chordCode(track: ChordTrack): string {
  if (track.muted) return `// ${track.name} (muted)`;
  const chordStr = track.chords
    .map(c => `[${c.join(',')}]`)
    .join(' ');
  const inner = `note("${chordStr}")
  .sound("${track.synth}")`;
  return `${modifiers(track.mod, inner)}${fxChain(track.id, track.fx)}`;
}

function trackCode(track: Track): string {
  if (track.type === 'drum')    return drumCode(track);
  if (track.type === 'melody')  return melodyCode(track);
  return chordCode(track as ChordTrack);
}

export function generateCode(): string {
  const { bpm, scale } = state;
  const activeTracks = state.tracks.filter(t => !t.muted);

  const lines = [
    `// Generated by VK IMMERSIVE DAW`,
    `// Scale: ${scale.root} ${scale.type}  BPM: ${bpm}`,
    ``,
    `setcpm(${Math.round(bpm / 4)})`,
    ``,
  ];

  activeTracks.forEach(t => {
    lines.push(`// ── ${t.name} ──`);
    lines.push(trackCode(t));
    lines.push('');
  });

  if (activeTracks.length > 1) {
    const names = activeTracks.map((_, i) => `p${i + 1}`).join(', ');
    lines.push(`// Stack all patterns`);
    lines.push(`stack(`);
    activeTracks.forEach((t, i) => {
      const comma = i < activeTracks.length - 1 ? ',' : '';
      lines.push(`  ${trackCode(t)}${comma}`);
    });
    lines.push(`)`);
  }

  return lines.join('\n');
}
